# SPDX-FileCopyrightText: 2023 Jerin Joy
#
# SPDX-License-Identifier: Apache-2.0

homebrew_packages:
  - bat
  - ccache
  - ctags
  - fd
  - fzf
  - git-delta
  - meson
  - mosh
  - neovim
  - starship
  - the_silver_searcher
  - tmux

fish_plugins:
  - aral/tide
  - jethrokuan/z
  - jorgebucaran/replay.fish
  - PatrickF1/fzf.fish
  - vitallium/tokyonight-fish
