#!/usr/bin/env zsh

# SPDX-FileCopyrightText: 2023 Jerin Joy
#
# SPDX-License-Identifier: Apache-2.0

set -e

CONFIG="base"
SUFFIX=".install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

case "$(uname)" in
    Darwin)
        OSNAME="macos"
        "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${OSNAME}${SUFFIX}" "${@}"
        ;;
    Linux)
        OSNAME="linux"
        "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${OSNAME}${SUFFIX}" --plugin-dir "{BASEDIR}/dotbot-apt" "${@}"
        ;;
    *)
        echo "Unsupported OS"
        exit 1
        ;;
esac


"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}${SUFFIX}" "${@}"
