#!/bin/zsh

# SPDX-FileCopyrightText: 2023 Jerin Joy
#
# SPDX-License-Identifier: Apache-2.0


# Pipefail explanation:
# https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425
set -euo pipefail

n=0
while test 0 -eq $? ; do
  n=$(($n+1))
  echo $n
  $@
done
