# SPDX-FileCopyrightText: 2023 Jerin Joy
#
# SPDX-License-Identifier: Apache-2.0

# Reference:
# https://gist.github.com/andersevenrud/015e61af2fd264371032763d4ed965b6
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g set-titles on                        # set terminal title
set -g set-titles-string '#h'
set-option -g prefix C-a
bind-key C-a last-window
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -s escape-time 0
set -g history-limit 1000000
set -g status-keys vi
setw -g mode-keys vi
unbind p
bind p paste-buffer
set -g set-clipboard on
# Copy-mode-vi keys that copy to system clipboard
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi Y send -X copy-line
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V   send -X select-line
bind -T copy-mode-vi C-v send -X rectangle-toggle
# quick entry for copy-mode
bind Escape copy-mode
# treat - and _ as part of words (nicer for code)
# (Remove - and _ from the separator list)
set -g word-separators ' @./:,;|=*()[]{}<>'
set -g @plugin 'tmux-plugins/tmux-yank'
bind j resize-pane -D 10
bind k resize-pane -U 10
bind h resize-pane -L 10
bind l resize-pane -R 10
bind \| split-window -h -c "#{pane_current_path}"
bind -  split-window -v -c "#{pane_current_path}"
set -g mouse on
bind m set -g mouse \; display-message "mouse: #{?mouse,ON,OFF}"
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
source-file ~/.tmux/themes/tokyo-night-day.tmux
set -g status-position bottom
set -g allow-passthrough on
run -b '~/.tmux/plugins/tpm/tpm'
