# SPDX-FileCopyrightText: 2023 Jerin Joy
#
# SPDX-License-Identifier: Apache-2.0

# --- Terminal ---
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g set-titles on
set -g set-titles-string '#h'
set -g allow-passthrough on

# --- General ---
set-option -g prefix C-a
bind-key C-a last-window
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -s escape-time 0
set -g history-limit 1000000
set -g mouse on

# --- Vi mode ---
set -g status-keys vi
setw -g mode-keys vi
set -g set-clipboard on
unbind p
bind p paste-buffer
bind Escape copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi Y send -X copy-line
set -g word-separators ' @./:,;|=*()[]{}<>'

# --- Navigation ---
bind h resize-pane -L 10
bind j resize-pane -D 10
bind k resize-pane -U 10
bind l resize-pane -R 10
bind \| split-window -h -c "#{pane_current_path}"
bind -  split-window -v -c "#{pane_current_path}"
bind m set -g mouse \; display-message "mouse: #{?mouse,ON,OFF}"

# --- Plugins ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

# --- Theme ---
source-file ~/.tmux/themes/ithaca-dark.tmux
set -g status-position bottom

run -b '~/.tmux/plugins/tpm/tpm'
