" SPDX-FileCopyrightText: 2023 Jerin Joy
"
" SPDX-License-Identifier: Apache-2.0

" --- General ---
syntax enable
filetype plugin indent on
set autoindent
set smartindent
set smarttab
set backspace=2
set undolevels=1000
set wildmenu
set hlsearch
set incsearch
set showmatch
set matchtime=5
set matchpairs=(:),{:},[:]
set laststatus=2
set cursorline
set colorcolumn=80
highlight ColorColumn ctermbg=Black
set mouse=

" --- Indentation ---
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2

" --- Cursor shape (DECSCUSR: bar/underline/block) ---
let &t_SI = "\e[5 q"
let &t_SR = "\e[3 q"
let &t_EI = "\e[1 q"
set guicursor=a:blinkon0

" --- Buffers ---
nnoremap <Tab> :bnext<CR>
nnoremap <S-Tab> :bprevious<CR>
nnoremap <C-k> :bd<CR>

" --- Airline ---
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ':t'
let g:airline#parts#ffenc#skip_expected_string='utf-8[unix]'
let g:airline_theme = 'tokyonight'
let g:airline_mode_map = {
    \ '__' : '-',
    \ 'n'  : 'N',
    \ 'i'  : 'I',
    \ 'R'  : 'R',
    \ 'c'  : 'C',
    \ 'v'  : 'V',
    \ 'V'  : 'V',
    \ '' : 'V',
    \ 's'  : 'S',
    \ }

" --- Tagbar ---
let g:tagbar_ctags_bin = "/opt/homebrew/bin/ctags"
nmap <C-n> :TagbarToggle<CR>

" --- FZF ---
nnoremap <C-p> :GFiles<Cr>
nnoremap <C-g> :Ag<Cr>

" --- Filetypes ---
au BufRead,BufNewFile *.isa setfiletype cpp
let g:vim_markdown_folding_disabled=1

" --- Autocommands ---
fun! TrimWhitespace()
    let l:save = winsaveview()
    keeppatterns %s/\s\+$//e
    call winrestview(l:save)
endfun
autocmd BufWritePre * :call TrimWhitespace()
autocmd VimResized * wincmd =

autocmd BufRead * call RONoEdit()
function! RONoEdit()
  if &readonly == 1
    set nomodifiable
  else
    set modifiable
  endif
endfunction

" --- Misc ---
let g:copilot_enabled = v:false

" --- vim-plug (auto-install) ---
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" --- Plugins ---
call plug#begin('~/.vim/plugged')
Plug 'ghifarit53/tokyonight-vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'preservim/tagbar'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'preservim/vim-markdown'
Plug 'tpope/vim-vinegar'
call plug#end()

" --- Theme ---
set termguicolors
let g:tokyonight_style = 'night'
colorscheme tokyonight
